data_root: "../../data/UCSF-PDGM"
output_dir: "./output"
output_name: "evaluation-rebalanced-plots"
seed: 42
os_bins: 4 
age_bins: [0, 58, 100]
reconstruction: 
  #results_path: "./output/reconstruction-csv_20241008_161359/reconstruction-csv_20241008_161359_reconstruction_results.csv" #If specified predictions will be loaded from this path
  lower_slice: 60
  upper_slice: 130
  sampling_mask: "radial"
  type: "T2"
  pathology: ["edema","non_enhancing"]
  model: 
    - network: "UNet"
      model_path: "./models/unet/checkpoints/unet_20240927_164753_epoch_8_best.pth"
classifiers:
  results_path: "./output/evaluation-rebalanced_20241016_085401/evaluation-rebalanced_20241016_085401_classifier_results.csv" #If specified predictions will be loaded from this path
  #results_path: "/lotterlab/users/matteo/code/recon_bias/output/classification-csv_20241008_161603_classifier_results.csv"
  lower_slice: 60
  upper_slice: 130
  type: "T2"
  pathology: ["edema","non_enhancing"]
  models: 
    - type: "TGradeBCEClassifier"
      network: "ResNet18"
      model_path: "./output/tgrade-rebalanced_20241015_143438/checkpoints/tgrade-rebalanced_20241015_143438_epoch_1.pth"
    - type: "TTypeBCEClassifier"
      network: "ResNet18"
      model_path: "./output/ttype-rebalanced_20241015_143317/checkpoints/ttype-rebalanced_20241015_143317_epoch_1.pth"
    - type: "NLLSurvClassifier"
      network: "ResNet18"
      model_path: "./output/os-rebalanced_20241015_151610/checkpoints/os-rebalanced_20241015_151610_epoch_1.pth"
    - type: "AgeCEClassifier"
      network: "ResNet18"
      model_path: "./output/age-rebalanced_20241015_151516/checkpoints/age-rebalanced_20241015_151516_epoch_1.pth"
    - type: "GenderBCEClassifier"
      network: "ResNet18"
      model_path: "./output/gender-rebalanced_20241015_143831/checkpoints/gender-rebalanced_20241015_143831_epoch_1.pth"

